### ISSUE TITLE
Head size

### ISSUE THREAD

**Issue by parthcmodi** [OpenBCI/ultracortex#10]
I noticed the STLs come in 3 different sizes (small, medium, and large).  What head sizes are they meant for?

**Comment by ThreeForm** [comment]
The frames correspond with these approximate head circumferences:
**Small = 50-55cm
Medium = 55-60cm
Large - 60-65cm**

The adjustment bolts create significant overlap between size ranges, so that the actual ranges overlap by 50%. A large headset fully adjusted inward (smaller) is approximately equivalent to a small headset adjusted outward (larger). A medium frame can fit an adult male about 90% of the time. Most women can wear an adjusted medium, but a small is usually a better fit.
