### ISSUE TITLE
Make the frame more 3D printer friendly

### ISSUE THREAD

**Issue by MCTaylor17** [OpenBCI/ultracortex#27]
I showed this to our printer guy and he suggested:
> Whoa! Too large, too much support required, I would think that with our printer there would be a 0% chance of success. 

I'm wondering if there is a way to make this project more friendly a wider variety of 3D printers.  

Perhaps break the frame into smaller components would help?

**Comment by ThreeForm** [comment]
The design is optimized to use very little support. We have printed hundreds of units with few issues. The Mark IV in particular, with its diagonal frame, requires far less support. One problem we are noticing is innapropriate slicer settings being used. If your print looks like this: https://mobile.twitter.com/ultracortex/status/746351060344799232?p=v then you are doing it wrong. The default Cura settings on that 1-shot Lulzbot print used more material for support than for the frame, and the result was so locked in it was impossible to remove without breaking. Our recommendation is to print in halves (STL's provided in the assembly guide). On Makerbot Rep2 we use something like 72 degree support angle, and no raft, but do add some brim adhesion pieces manually. I cannot make a universal recommendation because each printer is different, but look at the slice preview. If it makes you say "whoa" then change your settings.
