### ISSUE TITLE
High Density EEG?

### ISSUE THREAD

**Issue by jpellman** [OpenBCI/ultracortex#8]
This might be more of a suggestion for a future project than an improvement on the present iteration of Ultracortex, but I thought I'd throw it out there anyways.

A small, but growing, number of researchers are scanning with 32, 64, 128 and 256 electrode systems in order to employ a technique called source localization.  Source localization, as its name implies, allows you to pinpoint where EEG signals are coming from in a way that gives spatial resolution reminiscent of fMRI (though not comparable; fMRI voxel sizes can be as low as 1 mm isotropic, while EEG voxel sizes tend to be around 5 mm isotropic).  This technique, though not without controversy (what scientific methodology isn't?) is something I would be interested in seeing become more prevalent, as it seems to me that it would be much more cost effective to gather large datasets with EEG than with fMRI.

There are some high density nets on the market today, and while they're cheaper than fMRI, they can still be rather pricey (upwards of a thousand dollars per net).  In a time of dwindling scientific budgets, these costs can be prohibitive to some labs that otherwise might have wanted to try using this technique.  In light of this, I think that it would be neat if there were an open source alternative that labs could try out (even if it weren't necessarily as fully-featured as the nets that are out right now).

Here are a couple links for you to check out concerning source localization if your interested:
http://cdasr.mclean.harvard.edu/content/publications/LATN/BookChapters/Pizzagalli_HandbookPhysiology07.pdf
http://neuroimage.usc.edu/brainstorm/Tutorials#Background_readings

**Comment by ThreeForm** [comment]
@jpellman Thanks for the links. We recognize the need for higher density, and since you wrote your message we have developed a headset (Ultracortex M4) with about 3x the node count of the original Ultracortex. Since the current OpenBCI board has up to 16 channels (using Daisy expansion), multiple boards would be required to fully populate the nodes of the current design.

For customers who want to focus on one area with higher density, we can build a custom headset with any electrode placement required. This is most practical if you need several headsets, but we can also custom fit to a particular subject using CT/MRI if needed.
